---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown

 
### content configuration ###
home: "python's AcvtiveEXE component"
title: "python's AcvtiveEXE component"
keywords: "python's AcvtiveEXE component,stand-alone program,standalone,C,python,C#,C++,javascript,Go,Java,vbs...languages' calls"
description: "Use python's AcvtiveEXE component (12.5M) to generate a stand-alone program for C,python,C#,C++,javascript,Go,Java,vbs...languages' calls."
source_link: "https://chygfm.github.io/activeExe"
favicon: "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
email: "chygfm@foxmail.com"
qq: "1523338780"
#phone: "18520956787"
google_analytics_key: UA-51913082-4 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

